### ISSUE TITLE
can not start example

### ISSUE THREAD

**Issue by DawnyWu** [posabsolute/redux-flash-notification-example#1]
![image](https://cloud.githubusercontent.com/assets/949508/13949353/78a5a29e-f05f-11e5-8b09-1455fb25a200.png)

**Comment by DawnyWu** [comment]
well....I think this repo has nothing to do with redux-flash-notification, redux-flash-notification is not in package.json file

**Comment by posabsolute** [comment]
so this is embarrassing, I pushed over another repo... all fixed
